import groovy.json.JsonSlurper

def rtags = ""

def getTags() {
    // Get ImageStream data in JSON format
    //
    String result = sh(
      returnStdout: true, 
      script: "oc get is ${env.IMAGE_STREAM} -o json -n ${env.PROJECT_NAME}".toString()
    )

    // Parse JSON into a list of '\n' separated tags
    //echo "Result: ${result}"
    def json = new JsonSlurper().parseText(result)
    if ( json.spec.tags?.isEmpty() ) {
      error("Unable to fetch tags from '${env.IMAGE_STREAM}' ImageStream, in Project '${env.PROJECT_NAME}'")
    }
    else {
      String parsedOutTags = json.spec.tags.collect { it.name }.join('\n')
      echo "Available tags: ${parsedOutTags}"

      return parsedOutTags
    }


    // if (json.spec.tags == null || json.spec.tags.size == 0) {
    //   availableTags.add("unable to fetch tags for pipeline-tags")
    // } else {
    //   json.spec.tags.each { availableTags.add(it.name) }
    // }
    // return availableTags.join('\n')
}

try {
  node {
    stage("Get Tags") {
      timeout(time: 20, unit: 'SECONDS') {
        openshift.withCluster() {
          openshift.withProject("${env.PROJECT_NAME}") {
            rtags = getTags()
            echo rtags
          }
        }  
      }
    }
    stage("Get User Input") {
        timeout(time: 5, unit: 'MINUTES') {
            // Show the select input modal
          Map<String, String> userInput = input(message: 'Please Provide Parameters', ok: 'Next', parameters: 
            [
              choice(name: 'IMAGE_TAG', choices: rtags, description: 'Available Versions')
            ]
          )

          echo "============================="
          echo userInput.toString()
          echo "============================="
          
          env.IMAGE_TAG = userInput.IMAGE_TAG
        }
    }
    stage("Use Input") {
        echo "User input: ${env.IMAGE_TAG}"
    }
  }
} catch (err) {
  echo "in catch block"
  echo "Caught: ${err}"
  currentBuild.result = 'FAILURE'
  throw err
}